name: Laravel CI

on:
  push:
    branches:
      - main
      - develop
      - feature/*
    tags:
      - '*'           # triggers for all tags like 1.0, v1.0, v2.3.1 etc.

  pull_request:
    branches:
      - main
      - develop

jobs:
  laravel-ci:
    name: Laravel Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, mysql
          coverage: xdebug

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env and generate key
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h 127.0.0.1 --silent; do
            echo "Waiting for MySQL..."; sleep 5;
          done

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test

      - name: Notify on failure
        if: failure()
        run: |
          curl -X POST -H "Content-type: application/json" \
          --data "{\"text\":\" CI Failed on yousif30303/laravel-blog @ refs/heads/feature/github-check-discovery-modify8\"}" \
          ${{ secrets.SLACK_WEBHOOK }}

      - name: Generate test coverage report
        run: ./vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: SonarCloud Analysis (new action)
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
          SONAR_PROJECT_KEY: yousif30303_laravel-blog
          SONAR_ORGANIZATION: yousif30303

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Check SonarCloud Quality Gate result
        run: |
          echo "Waiting for SonarCloud Quality Gate result..."
          for i in {1..10}; do
            sleep 10
            STATUS=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
              "https://sonarcloud.io/api/qualitygates/project_status?projectKey=yousif30303_laravel-blog" \
              | jq -r '.projectStatus.status')
            echo "Status: $STATUS"
            if [ "$STATUS" == "OK" ]; then
              echo "✅ Quality Gate Passed!"
              exit 0
            elif [ "$STATUS" == "ERROR" ]; then
              echo "❌ Quality Gate Failed!"
              exit 1
            fi
          done
          echo "❗ Timed out waiting for Quality Gate result."
          exit 1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set Docker Image Tag (from tag or branch)
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          fi

      - name: Build Docker Image
        if: success()
        run: docker build -t yousif30303/laravel-app:${{ env.IMAGE_TAG }} .

      - name: Push Docker Image
        run: docker push yousif30303/laravel-app:${{ env.IMAGE_TAG }}

      - name: Run Integration Tests
        run: ./vendor/bin/phpunit --testsuite=Integration

      - name: Install Enlightn Security Checker
        run: composer require --dev enlightn/security-checker

      - name: Run Security Scan
        run: ./vendor/bin/security-checker security:check composer.lock

      - name: Run Seeder
        run: php artisan db:seed --force

      - name: Serve Laravel app
        run: php artisan serve --host=127.0.0.1 --port=8000 &

      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg software-properties-common
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Run k6 Load Test
        run: k6 run tests/load/load-test.js




